name: drlnd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - tensorflow
  - cuda92
  - jupyter
  - notebook
  - Pillow
  - PyOpenGL
  - matplotlib
  - pytest
  - docopt
  - pyyaml
  - pandas
  - scipy
  - ipykernel
  - tqdm
  - pylint
  - pip:
      - gym[atari]
      - git+https://github.com/Kojoley/atari-py.git
      - torchvision
      - ./python
      - jupyter-http-over-ws
